name = "incrementalGP"
uuid = "3642aa9e-ec3c-4cc7-84b8-4118a08652e8"
authors = ["Felix Benning <felix.benning@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
